version: "3.1"

services:
  app:
    container_name: testcont
    image: application
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgres
  dbpostgres:
    image: postgres
    volumes:
      - /home/ivan/Documents/forTest/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=57az9916
      - POSTGRES_USER=postgres
      - POSTGRES_DB=filesystem